# Tarea 1 - Sistemas Operativos 1 (CI-3825)
# Juan Andres Cuevas 19-10056

# Variables
CC = gcc
CFLAGS = -o
TARGET = main-comp
SRC = main.c

# Reglas
all:
	$(CC) $(SRC) $(CFLAGS) $(TARGET)

.PHONY : clean

clean :
	rm -rf $(TARGET)