# Compilar en C, el archivo main.c
# y generar el ejecutable main

# Variables
CC = gcc
CFLAGS = -o
TARGET = main-comp
SRC = main.c

# Reglas
all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(TARGET) $(SRC)